% =========================================================================
% FAST Weight Optimization for Plasma Path Sorting (Multi-Objective)
% + Export to File, Heavy Pressure Prioritization & Dual Custom Seeding
% + Automatically Aggregates Outputs from 02_kcenters_point_filler.m
% =========================================================================
clear; clc; close all;

fprintf('\n======================================================\n');
fprintf('STARTING MINIMAX PATH SEQUENCER\n');
fprintf('======================================================\n');

% =========================================================================
% 1. AUTOMATIC DATA AGGREGATION FROM STEP 2 (POINT FILLER)
% =========================================================================
% Look for the cluster files generated by 02_kcenters_point_filler.m
filled_files = dir('cluster_dpOnt_*_final_fill.txt');
raw_data = [];

if ~isempty(filled_files)
    fprintf('Detected %d cluster files from the Point Filler step. Aggregating...\n', length(filled_files));
    for i = 1:length(filled_files)
        temp_data = readmatrix(filled_files(i).name);
        raw_data = [raw_data; temp_data];
    end
    fprintf('Successfully combined %d total points.\n', size(raw_data, 1));
else
    % Fallback if the user already combined them manually
    fallback_filename = 'v10_Ar_eth_dataset_full.txt';
    if exist(fallback_filename, 'file')
        fprintf('Cluster files not found. Loading fallback file: %s\n', fallback_filename);
        raw_data = readmatrix(fallback_filename);
    else
        error('No data found! Please run 02_kcenters_point_filler.m first or provide a valid .txt file.');
    end
end

num_points_total = size(raw_data, 1);
num_cols_total = size(raw_data, 2);

% 2. Feature Extraction & Normalization for the full dataset
% Always uses the first 4 columns: Power, Pressure, Feed, Vbias
power = raw_data(:, 1);
pressure = raw_data(:, 2);
feed = raw_data(:, 3);

% Calculate E/N Proxy (Power / Pressure)
EN_proxy = power ./ pressure; 
augmented_data = [raw_data(:, 1:4), EN_proxy];
norm_matrix = zeros(size(augmented_data));

min_vals = min(augmented_data(:, 1:4), [], 1);
max_vals = max(augmented_data(:, 1:4), [], 1);
ranges = max_vals - min_vals;
ranges(ranges == 0) = 1; % Prevent division by zero

for col = 1:5
    c_min = min(augmented_data(:, col));
    c_max = max(augmented_data(:, col));
    if c_max ~= c_min
        norm_matrix(:, col) = (augmented_data(:, col) - c_min) / (c_max - c_min);
    end
end

% Define our 2 target mother configurations: [Power, Pressure, Feed, Vbias]
targets = [
    1000, 0.018, 30, 100;  % Mother 2
    1000, 0.018, 30, 100   % Mother 3
];
target_suffixes = {'M2', 'M3'};
target_names = {'Mother 2', 'Mother 3'};

% =========================================================================
% 3. SPLIT DATASET BASED ON PURE PHYSICAL PROXIMITY
% =========================================================================
norm_targets = zeros(2, 4);
for t_idx = 1:2
    norm_targets(t_idx, :) = (targets(t_idx, :) - min_vals(1:4)) ./ ranges(1:4);
end

% Compute Euclidean distance from all points to M2 and M3
dist_to_M2 = sqrt(sum((norm_matrix(:, 1:4) - norm_targets(1, :)).^2, 2));
dist_to_M3 = sqrt(sum((norm_matrix(:, 1:4) - norm_targets(2, :)).^2, 2));

% Assign each point to the Mother it is actually closest to
mask_M2 = dist_to_M2 <= dist_to_M3;
mask_M3 = ~mask_M2;

fprintf('Splitting dataset based on physical proximity...\n');
fprintf(' -> %d points assigned to Mother 2\n', sum(mask_M2));
fprintf(' -> %d points assigned to Mother 3\n', sum(mask_M3));

% Failsafe: Ensure neither subset is empty
if sum(mask_M2) == 0 || sum(mask_M3) == 0
    warning('One of the Mother targets captured 0 points! Check target coordinates.');
end

% =========================================================================
% 4. RUN OPTIMIZATION FOR EACH SUBSET
% =========================================================================
% Loop over both target seeds to run individual optimizations on their halves
for t_idx = 1:2
    % Define which mask to use for this iteration
    if t_idx == 1
        group_mask = mask_M2;
    else
        group_mask = mask_M3;
    end
    
    % Extract the points for this specific mother
    sub_raw_data = raw_data(group_mask, :);
    sub_norm_matrix = norm_matrix(group_mask, :);
    sub_EN_proxy = EN_proxy(group_mask);
    sub_feed = feed(group_mask);
    sub_pressure = pressure(group_mask);
    sub_num_points = size(sub_raw_data, 1);
    
    t_coords = targets(t_idx, :);
    t_suffix = target_suffixes{t_idx};
    t_name = target_names{t_idx};
    
    % FIND TARGET SEED STARTING INDEX WITHIN THIS SUBSET
    dists_to_mother = sum((sub_norm_matrix(:, 1:4) - norm_targets(t_idx, :)).^2, 2);
    [~, start_idx] = min(dists_to_mother);
    
    fprintf('\n------------------------------------------------------\n');
    fprintf('OPTIMIZATION PIPELINE: %s Subset\n', upper(t_name));
    fprintf('------------------------------------------------------\n');
    fprintf('Target Parameters: [Power = %.0f W, Press = %.4f Torr, Feed = %.0f sccm, Vbias = %.0f V]\n', ...
        t_coords(1), t_coords(2), t_coords(3), t_coords(4));
    fprintf('Closest point in this half located at Subset Row: %d\n', start_idx);
    fprintf('Actual coordinates: Power = %.2f W, Press = %.4f Torr, Feed = %.2f sccm, Vbias = %.2f V\n\n', ...
        sub_raw_data(start_idx, 1), sub_raw_data(start_idx, 2), ...
        sub_raw_data(start_idx, 3), sub_raw_data(start_idx, 4));
        
    % Define Training Parameters & Fatal Limits
    iterations = 30000; % Safe to use 5000+ with parfor
    fatal_EN_jump = 14000; 
    fatal_flow_jump = 15;  
    fatal_press_jump = 0.005; % Constraint to penalize delta pressure > 0.005 Torr
    disp('Commencing search across weight space...');
    
    % Pre-allocate arrays for parfor loop
    fitness_scores = zeros(iterations, 1);
    max_EN_jumps = zeros(iterations, 1);
    max_flow_jumps = zeros(iterations, 1);
    max_press_jumps = zeros(iterations, 1); 
    weights_history = zeros(iterations, 5);
    
    % Run Optimization Loop (MULTI-THREADED)
    tic;
    parfor iter = 1:iterations
        % Let all weights search a wide 0-10 scale
        w_P  = rand() * 10;
        w_p  = rand() * 10; 
        w_Q  = rand() * 10; 
        w_V  = 0; 
        w_EN = rand() * 10;
        
        current_weights = [w_P, w_p, w_Q, w_V, w_EN];
        weighted_norm_matrix = sub_norm_matrix .* current_weights;
        
        % Perform Nearest-Neighbor Sort starting at the selected mother index
        visited = false(sub_num_points, 1);
        sorted_indices = zeros(sub_num_points, 1);
        current_idx = start_idx; % Seeded start index
        sorted_indices(1) = current_idx;
        visited(current_idx) = true;
        
        for step = 2:sub_num_points
            current_coords = weighted_norm_matrix(current_idx, :);
            
            % VECTORIZED DISTANCE CALCULATION
            unvisited_mask = ~visited;
            unvisited_indices = find(unvisited_mask);
            
            diffs = weighted_norm_matrix(unvisited_mask, :) - current_coords;
            dists = sum(diffs.^2, 2); 
            
            [~, min_idx_relative] = min(dists);
            next_idx = unvisited_indices(min_idx_relative);
            
            current_idx = next_idx;
            sorted_indices(step) = current_idx;
            visited(current_idx) = true;
        end
        
        % Evaluate Fitness for this subset
        sorted_EN = sub_EN_proxy(sorted_indices);
        max_EN_jump = max(abs(diff(sorted_EN)));
        
        sorted_feed = sub_feed(sorted_indices);
        max_flow_jump = max(abs(diff(sorted_feed)));
        
        sorted_press = sub_pressure(sorted_indices);
        max_press_jump = max(abs(diff(sorted_press)));
        
        % Fitness function prioritizing avoiding crashes across three variables
        fitness_score = (max_EN_jump / fatal_EN_jump) + ...
                        (max_flow_jump / fatal_flow_jump) + ...
                        (max_press_jump / fatal_press_jump);
        
        % Check if any trajectory boundary exceeds critical thresholds
        if max_EN_jump > fatal_EN_jump || ...
           max_flow_jump > fatal_flow_jump || ...
           max_press_jump > fatal_press_jump
            fitness_score = fitness_score + 1000;
        end
        
        % Store iteration results
        fitness_scores(iter) = fitness_score;
        max_EN_jumps(iter) = max_EN_jump;
        max_flow_jumps(iter) = max_flow_jump;
        max_press_jumps(iter) = max_press_jump;
        weights_history(iter, :) = current_weights;
    end
    search_time = toc;
    
    % Extract best result
    [best_fitness, best_idx] = min(fitness_scores);
    best_max_EN = max_EN_jumps(best_idx);
    best_max_flow = max_flow_jumps(best_idx);
    best_max_press = max_press_jumps(best_idx);
    best_weights = weights_history(best_idx, :);
    
    % Display Results
    fprintf('\n=== TRAINING COMPLETE (%s Subset: %.2f seconds) ===\n', t_name, search_time);
    fprintf('Target Limits: E/N < %d | Flow < %d sccm | Pressure Jump < %.4f Torr\n', ...
        fatal_EN_jump, fatal_flow_jump, fatal_press_jump);
    fprintf('Best Path Max E/N Jump:   %.0f\n', best_max_EN);
    fprintf('Best Path Max Flow Jump:  %.1f sccm\n', best_max_flow);
    fprintf('Best Path Max Press Jump: %.5f Torr\n\n', best_max_press);
    
    if best_max_EN < fatal_EN_jump && ...
       best_max_flow < fatal_flow_jump && ...
       best_max_press < fatal_press_jump
        fprintf('SUCCESS: %s path completely avoids all crash thresholds.\n', t_name);
    else
        fprintf('WARNING: %s dataset is too sparse. Could not entirely avoid a harsh jump.\n', t_name);
    end
    
    fprintf('\nOPTIMIZED WEIGHTS FOR %s:\n', upper(t_name));
    fprintf('Power Weight:    %.3f\n', best_weights(1));
    fprintf('Pressure Weight: %.3f\n', best_weights(2));
    fprintf('Feed Weight:     %.3f\n', best_weights(3));
    fprintf('Vbias Weight:    %.3f\n', best_weights(4));
    fprintf('E/N Proxy Weight:%.3f\n', best_weights(5));
    
    % =========================================================================
    % 5. RE-SORT, VISUALIZE, AND EXPORT
    % =========================================================================
    % Re-run sort with best weights to get final output order
    weighted_norm_matrix = sub_norm_matrix .* best_weights;
    visited = false(sub_num_points, 1);
    final_sorted_indices = zeros(sub_num_points, 1);
    current_idx = start_idx; % Seeded start index
    final_sorted_indices(1) = current_idx; 
    visited(current_idx) = true;
    
    for step = 2:sub_num_points
        unvisited_mask = ~visited;
        unvisited_indices = find(unvisited_mask);
        diffs = weighted_norm_matrix(unvisited_mask, :) - weighted_norm_matrix(current_idx, :);
        dists = sum(diffs.^2, 2); 
        [~, min_idx_relative] = min(dists);
        current_idx = unvisited_indices(min_idx_relative);
        final_sorted_indices(step) = current_idx; 
        visited(current_idx) = true;
    end
    
    % Extract the fully sorted row data for this subset (Retains ALL original columns)
    sorted_data_output = sub_raw_data(final_sorted_indices, :);
    
    % --- Plot 1: E/N Evaluation ---
    figure('Name', sprintf('Profile %s: E/N Jumps', t_suffix));
    plot(diff(sub_EN_proxy), '-o', 'Color', [0.8 0.3 0.3], 'DisplayName', 'Original E/N Jumps'); hold on;
    plot(diff(sub_EN_proxy(final_sorted_indices)), '-*g', 'LineWidth', 1.5, 'DisplayName', 'Optimized E/N Jumps');
    yline(fatal_EN_jump, '--r', 'Fatal Crash Threshold', 'LineWidth', 2);
    yline(-fatal_EN_jump, '--r', 'LineWidth', 2);
    xlabel('Step Number'); ylabel('Magnitude of E/N Jump (\Delta W/Torr)');
    title(sprintf('%s Subset Trajectory (E/N Proxy)', t_name)); legend('Location', 'best'); grid on;
    
    % --- Plot 2: Flow Evaluation ---
    figure('Name', sprintf('Profile %s: Feed Gas Flow', t_suffix));
    plot(diff(sub_feed), '-o', 'Color', [0.8 0.3 0.3], 'DisplayName', 'Original Flow Jumps'); hold on;
    plot(diff(sub_feed(final_sorted_indices)), '-*b', 'LineWidth', 1.5, 'DisplayName', 'Optimized Flow Jumps');
    yline(fatal_flow_jump, '--r', 'Fatal Flow Threshold', 'LineWidth', 2);
    yline(-fatal_flow_jump, '--r', 'LineWidth', 2);
    xlabel('Step Number'); ylabel('Magnitude of Flow Jump (\Delta sccm)');
    title(sprintf('%s Subset Trajectory (Feed Gas)', t_name)); legend('Location', 'best'); grid on;
    
    % --- Plot 3: Pressure Evaluation ---
    figure('Name', sprintf('Profile %s: Pressure Jumps', t_suffix));
    plot(diff(sub_pressure), '-o', 'Color', [0.8 0.3 0.3], 'DisplayName', 'Original Pressure Jumps'); hold on;
    plot(diff(sub_pressure(final_sorted_indices)), '-*m', 'LineWidth', 1.5, 'DisplayName', 'Optimized Pressure Jumps');
    yline(fatal_press_jump, '--r', 'Fatal Pressure Jump Threshold', 'LineWidth', 2);
    yline(-fatal_press_jump, '--r', 'LineWidth', 2);
    xlabel('Step Number'); ylabel('Magnitude of Pressure Jump (\Delta Torr)');
    title(sprintf('%s Subset Trajectory (Pressure)', t_name)); legend('Location', 'best'); grid on;
    
    % --- FILE EXPORT ---
    output_filename = sprintf('AGGREGATED_OPTIMIZED_SEQUENCE_%s.txt', t_suffix);
    disp(['Writing optimized subset data to: ', output_filename]);
    
    fid = fopen(output_filename, 'w');
    % Dynamically construct format string based on column count
    num_cols = size(sorted_data_output, 2);
    format_str = [repmat('%.6f\t', 1, num_cols-1), '%.6f\n'];
    for r = 1:sub_num_points
        fprintf(fid, format_str, sorted_data_output(r, :));
    end
    fclose(fid);
    disp(['File export complete for ', t_name, ' Subset!']);
end